---
# tasks file for will.calico
- name: check for install dir
  file: 
    path='{{install_dir}}' 
    state=directory 
    mode=0755

- name: check for installation of calico
  become: yes
  stat:
    path: '{{install_dir}}/calicoctl'
  changed_when: false
  register: calico_binary_dir

- when: not calico_binary_dir.stat.exists
  block:
    - name: download calico
      become: yes
      become_user: root
      get_url:
        url: 'https://github.com/projectcalico/calicoctl/releases/download/v{{target_version}}/calicoctl'
        dest: '{{install_dir}}/calicoctl'
        mode: 0755

- name: link calico and calicoctl
  become: yes
  become_user: root
  file:
    src: '{{install_dir}}/{{item}}'
    dest: '/usr/local/bin/{{item}}'
    state: link
  with_items:
    - calicoctl

- name: Set peers conf
  sudo: yes
  template: src=calico.service dest=/lib/systemd/system/calico.service
  notify:
    - Reload systemd
    
